services:
  # mysql 설정
  infragen-mysql:
    image: 'mysql:8.0'
    container_name: infragen-mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      TZ: Asia/Seoul
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    ports:
      - '127.0.0.1:3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - infragen-network

  # redis 설정
  infragen-redis:
    image: 'redis:alpine'
    container_name: infragen-redis
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    restart: always
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - infragen-network

# 각 서비스들이 서로 통신할 수 있는 가상의 네트워크 정의
networks:
  infragen-network:
    driver: bridge

# 데이터 보존을 위한 명명된 볼륨 정의
volumes:
  mysql_data:
  redis_data:
