server:
  port: 8080

# spring 컨테이너 설정 관련
spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: infragen

  datasource:
    url: ${MYSQL_DATABASE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        jdbc.batch_size: 50
        order_inserts: true
        order_updates: true
        jdbc.batch_versioned_data: true

  servlet:
    encoding:
      charset: UTF-8

# jwt 설정 관련
jwt:
  secret: ${JWT_SECRET}
  access-token:
    expiration-time: 3600000 # 1시간 (밀리초 단위)
  refresh-token:
    expiration-time: 1209600000 # 14일
  dev-token:
    expiration-time: 1209600000
  issuer: infra-gen

cors:
  allowed-origins: http://localhost:3000,http://localhost:5173,https://*.vercel.app

# kakao 설정 관련
kakao:
  client-id: ${KAKAO_CLIENT_ID}
  redirect-uri: ${KAKAO_REDIRECT_URI}
  authorization-uri: https://kauth.kakao.com/oauth/authorize
  token-uri: https://kauth.kakao.com/oauth/token
  user-info-uri: https://kapi.kakao.com/v2/user/me

# 커스텀 비동기 처리 및 스케줄러 관련
notification:
  async:
    core-pool-size: ${ASYNC_CORE_POOL_SIZE:5}
    max-pool-size: ${ASYNC_MAX_POOL_SIZE:10}
    queue-capacity: ${ASYNC_QUEUE_CAPACITY:50}